/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* cells_not_processed =  1  *)
(* src = "df.v:1" *)
module df(in, clk, clr, out);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  (* src = "df.v:3" *)
  input clk;
  (* src = "df.v:3" *)
  input clr;
  (* src = "df.v:2" *)
  input [12:0] in;
  (* src = "df.v:4" *)
  output [12:0] out;
  (* src = "df.v:13" *)
  DFF_X1 _26_ (
    .CK(clk),
    .D(in[0]),
    .Q(out[0]),
    .QN(_24_)
  );
  (* src = "df.v:13" *)
  DFF_X1 _27_ (
    .CK(clk),
    .D(in[1]),
    .Q(out[1]),
    .QN(_23_)
  );
  (* src = "df.v:13" *)
  DFF_X1 _28_ (
    .CK(clk),
    .D(in[2]),
    .Q(out[2]),
    .QN(_22_)
  );
  (* src = "df.v:13" *)
  DFF_X1 _29_ (
    .CK(clk),
    .D(in[3]),
    .Q(out[3]),
    .QN(_21_)
  );
  (* src = "df.v:13" *)
  DFF_X1 _30_ (
    .CK(clk),
    .D(in[4]),
    .Q(out[4]),
    .QN(_20_)
  );
  (* src = "df.v:13" *)
  DFF_X1 _31_ (
    .CK(clk),
    .D(in[5]),
    .Q(out[5]),
    .QN(_19_)
  );
  (* src = "df.v:13" *)
  DFF_X1 _32_ (
    .CK(clk),
    .D(in[6]),
    .Q(out[6]),
    .QN(_18_)
  );
  (* src = "df.v:13" *)
  DFF_X1 _33_ (
    .CK(clk),
    .D(in[7]),
    .Q(out[7]),
    .QN(_17_)
  );
  (* src = "df.v:13" *)
  DFF_X1 _34_ (
    .CK(clk),
    .D(in[8]),
    .Q(out[8]),
    .QN(_16_)
  );
  (* src = "df.v:13" *)
  DFF_X1 _35_ (
    .CK(clk),
    .D(in[9]),
    .Q(out[9]),
    .QN(_15_)
  );
  (* src = "df.v:13" *)
  DFF_X1 _36_ (
    .CK(clk),
    .D(in[10]),
    .Q(out[10]),
    .QN(_14_)
  );
  (* src = "df.v:13" *)
  DFF_X1 _37_ (
    .CK(clk),
    .D(in[11]),
    .Q(out[11]),
    .QN(_13_)
  );
  (* src = "df.v:13" *)
  DFF_X1 _38_ (
    .CK(clk),
    .D(in[12]),
    .Q(out[12]),
    .QN(_25_)
  );
  (* src = "df.v:6" *)
  DFF_X1 _39_ (
    .CK(clr),
    .D(1'h0),
    .Q(out[0]),
    .QN(_12_)
  );
  (* src = "df.v:6" *)
  DFF_X1 _40_ (
    .CK(clr),
    .D(1'h0),
    .Q(out[1]),
    .QN(_11_)
  );
  (* src = "df.v:6" *)
  DFF_X1 _41_ (
    .CK(clr),
    .D(1'h0),
    .Q(out[2]),
    .QN(_10_)
  );
  (* src = "df.v:6" *)
  DFF_X1 _42_ (
    .CK(clr),
    .D(1'h0),
    .Q(out[3]),
    .QN(_09_)
  );
  (* src = "df.v:6" *)
  DFF_X1 _43_ (
    .CK(clr),
    .D(1'h0),
    .Q(out[4]),
    .QN(_08_)
  );
  (* src = "df.v:6" *)
  DFF_X1 _44_ (
    .CK(clr),
    .D(1'h0),
    .Q(out[5]),
    .QN(_07_)
  );
  (* src = "df.v:6" *)
  DFF_X1 _45_ (
    .CK(clr),
    .D(1'h0),
    .Q(out[6]),
    .QN(_06_)
  );
  (* src = "df.v:6" *)
  DFF_X1 _46_ (
    .CK(clr),
    .D(1'h0),
    .Q(out[7]),
    .QN(_05_)
  );
  (* src = "df.v:6" *)
  DFF_X1 _47_ (
    .CK(clr),
    .D(1'h0),
    .Q(out[8]),
    .QN(_04_)
  );
  (* src = "df.v:6" *)
  DFF_X1 _48_ (
    .CK(clr),
    .D(1'h0),
    .Q(out[9]),
    .QN(_03_)
  );
  (* src = "df.v:6" *)
  DFF_X1 _49_ (
    .CK(clr),
    .D(1'h0),
    .Q(out[10]),
    .QN(_02_)
  );
  (* src = "df.v:6" *)
  DFF_X1 _50_ (
    .CK(clr),
    .D(1'h0),
    .Q(out[11]),
    .QN(_01_)
  );
  (* src = "df.v:6" *)
  DFF_X1 _51_ (
    .CK(clr),
    .D(1'h0),
    .Q(out[12]),
    .QN(_00_)
  );
endmodule
